[project]
name = "github-backup"
version = "1.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["requests>=2.32.3"]

[dependency-groups]
dev = ["setuptools>=78.1.0"]
